artifacts_root : artifacts

data ingestion:
  root_dir: artifact/data_ingestion
  source: data/train.csv
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_ingestion/status.txt

data validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status/txt

feature_extraction:
  root_dir: artifacts/feature_extraction
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/feature_extraction/status.txt

nested_cross_val:
  rot_dir: artifacts/nested_cross_val
  extracted_features: artifacts/feature_extraction
  random_search_models_rf: artifacts/nested_cross_val/random_search_models/random_forest
  model_cache_rf: artifacts/nested_cross_val/model_cache_rf
  train_data_path: artifacts/nested_cross_val/data_for_final_train
  test_data_path: artifacts/nested_cross_val/data_for_final_train
  model_name: model.joblib
  metric_file_name_rf: artifacts/nested_cross_val/random_search_model/random_forest/metrics
  best_model_params_rf: artifacts/nested_cross_val/random_search_models/random_forest/best_model_params
  STATUS_FILE: artifacts/nested_cross_val/status.txt


feature_engineering:
  root_dir: artifacts/feature_engneering
  train_data_path: artifacts/nested_cross_val/data_for_final_train
  test_data_path: artifacts/nested_cross_val/data_for_final_train
  STATUS_FILE: artifacts/feature_engineering/status.txt

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/feature_engineering
  test_data_path: artifacts/feature_engineering
  final_model_name: artifacts/model_trainer/final_model.joblib
  metric_file_name_rf: artifacts/nested_cross_val/random_search_models/random_forest/metrics
  best_model_params_rf: artifacts/nested_cross_val/random_search_models/random_forest/best_model_params
  STATUS_FILE: artifacts/model_trainer/status.txt

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/feature_engineering
  model_path: artifacts/model_trainer/final_model.joblib
  metric_file: artifacts/model_evaluation/metrics
  STATUS_FILE: artifacts/model_evaluation/status.txt